language: node_js

sudo: required

services:
- docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose -f docker/docker-compose.yml pull

script:
- docker-compose -f docker/docker-compose.yml rm -f
- docker-compose -f docker/docker-compose.yml up -d
- sleep 10
- curl -vv "http://localhost:8080/v1/hello"
